
  CC = g++
 

  CXXFLAGS  = -g 
  
  

	
	

  #TARGET = host
 	
  all: $(TARGET)
 
  $(TARGET): $(TARGET).cpp
	$(CC) $(CXXFLAGS) -o $(TARGET) $(TARGET).cpp botKW.cpp gen.cpp botjk.cpp botjp.cpp functions.cpp botMS.cpp
  clean:
	$(RM) $(TARGET)
