
 CC = g++
 

 CXXFLAGS  = -g 
  
  

	
	

 #TARGET = host
 	
 all: host samo
 
 host: 
	$(CC) $(CXXFLAGS) -o host host.cpp botKW.cpp gen.cpp botjk.cpp botjp.cpp functions.cpp botMS.cpp
 samo: 
	$(CC) $(CXXFLAGS) -o samo samo.cpp botKW.cpp gen.cpp botjk.cpp botjp.cpp functions.cpp botMS.cpp
 clean:
	$(RM) host samo
